Repository tracked-tools/tracked-toolbox, pull requests merged in 2022-03, with the labels that each got.

#53 Add ability to pass a custom comparator to `dedupe-tracked`
  addon/index.js
  tests/unit/dedupe-tracked-test.js
Labels: enhancement

#43 Update npmignore file
  .npmignore
Labels: internal

#45 Switch ember-cli-eslint -> eslint and upgrade eslint-plugins
  .eslintrc.js
  package.json
  yarn.lock
Labels: internal

#50 Run ember-cli-update to v3.28.3 to align with the latest addon blueprint
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  config/ember-try.js
  ember-cli-build.js
  package.json
  testem.js
  tests/dummy/app/app.js
  tests/dummy/app/components/custom-input.hbs
  tests/dummy/app/router.js
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  tests/index.html
  yarn.lock
Labels: internal

#57 Move `ember-cli-htmlbars` to `devDependencies`
  package.json
Labels: enhancement

#58 Bump eslint-plugin-qunit from 7.0.0 to 7.2.0
  package.json
  tests/unit/cached-test.js
  tests/unit/dedupe-tracked-test.js
  tests/unit/local-copy-test.js
  tests/unit/tracked-reset-test.js
  yarn.lock
Labels: dependencies

#44 Drop Node.js 8, 10, 11, 13, 15 support
  README.md
  package.json
Labels: dependencies, breaking

#59 Run ember-cli-update to v4.2 to align with the latest addon blueprint
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  CONTRIBUTING.md
  config/ember-try.js
  package.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  yarn.lock
Labels: internal
